server:
  servlet:
    context-path: /pegasus-service
  port:
    8020
spring:
  application:
    name: pegasus-service
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33060/sample
    username: mysql-app
    password: mysql-app
  cache:
    type: redis
  redis:
    host: localhost
    port: 16379
    database: 0
    password: 
    timeout: 3000
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
application:
  version: v1.0
  business:
    users:
      search-limit-count: 500
      page-size: 10
datalinkage:
  url: http://localhost:8050/pegasus-datalinkage/messages
  publish: /publish
  subscription: /subscription
tasks:
  sleep-tasks:
    initial-delay: 1000
    fixed-rate: 1000
    sleep-millisecond: 1000
    max-sleep-millisecond: 10000
    task-on: false
log:
  base-directory: C:/work/logs
